version: "3.9"

services:
  app:
    build: .
    image: muhohoweb/image-processor
    container_name: image_processor_app
    ports:
      - "80:5000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
