name: CI/CD Deploy to AWS Lightsail Container Service

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: muhohoweb/image-processor
  SERVICE_NAME: muhohoweb-service

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Lightsail Container Service
        run: |
          CONTAINERS_JSON=$(jq -n \
            --arg image "$IMAGE_NAME:latest" \
            --arg key "${{ secrets.OPENAI_API_KEY }}" \
            '[{
              containerName: "muhohoweb-container",
              image: $image,
              environment: {
                OPENAI_API_KEY: $key
              },
              ports: {
                "5000": "HTTP"
              }
            }]'
          )

          echo "Deploying with containers config:"
          echo "$CONTAINERS_JSON"

          aws lightsail create-container-service-deployment \
            --service-name "$SERVICE_NAME" \
            --containers "$CONTAINERS_JSON" \
            --public-endpoint '{"containerName":"muhohoweb-container","containerPort":5000,"healthCheck":{"path":"/"}}'

